# ã‚·ã‚§ãƒ«ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã®é–“ã«ç©ºè¡Œã‚’è¿½åŠ ã—ã¾ã™
add_newline = true

[character]
# "â¯" è¨˜å·ã‚’ä»»æ„ã®æ–‡å­—åˆ—ã«å¤‰æ›
success_symbol = "ğŸ“¢"

# packageãƒ¢ã‚¸ãƒ¥ãƒ¼ãƒ«ã‚’ç„¡åŠ¹ã«ã—ã€ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã‹ã‚‰å®Œå…¨ã«éš ã™
[package]
disabled = true

# ãƒ¡ãƒ¢ãƒªä½¿ç”¨é‡
[memory_usage]
disabled = false
threshold = -1
symbol = "ğŸ"
style = "bold italic dimmed fg:white"
format = " $symbol [${ram}]($style) "

# ç›´å‰ã®ã‚³ãƒãƒ³ãƒ‰ã«æ›ã‹ã£ãŸæ™‚é–“ã®è¡¨ç¤º
[cmd_duration]
disabled = false
min_time = 1_000
show_milliseconds = true
format = "took [$duration](bold yellow)"

# ç¾åœ¨æ™‚åˆ»
[time]
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%T"
style = "bold yellow"
